/* 
 * Copyright 2026 Giuseppe Scotto Lavina
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { join } from "node:path";
import { mkdir } from "node:fs/promises";

/**
 * Generates a basic TypeScript library project structure.
 */
export async function generateTSLib(name: string, targetDir: string, registryUrl: string): Promise<void> {
    // Determine scope and safe name
    const validName = name.toLowerCase().replace(/[^a-z0-9@/-]/g, "-");

    // 1. Create directories
    await mkdir(targetDir, { recursive: true });
    await mkdir(join(targetDir, "src"), { recursive: true });

    // 2. package.json
    const pkgJson = {
        name: validName,
        version: "0.1.0",
        main: "dist/index.js",
        types: "dist/index.d.ts",
        files: ["dist"],
        scripts: {
            "build": "tsc",
            "prepublishOnly": "npm run build",
            "test": "echo \"Error: no test specified\" && exit 1"
        },
        description: "Scaffolded by AgentRegistry",
        keywords: ["agentregistry"],
        author: "",
        license: "Apache-2.0",
        devDependencies: {
            "typescript": "^5.0.0"
        }
    };

    // 3. tsconfig.json
    const tsConfig = {
        compilerOptions: {
            target: "es2020",
            module: "commonjs",
            declaration: true,
            outDir: "./dist",
            strict: true,
            esModuleInterop: true,
            forceConsistentCasingInFileNames: true,
            skipLibCheck: true
        },
        include: ["src"],
        exclude: ["node_modules", "dist"]
    };

    // 4. .npmrc (Pointing to local registry)
    const npmRc = `registry=${registryUrl}\n`;

    // 5. src/index.ts
    const indexTs = `/**\n * Example function\n */\nexport function hello(): string {\n    return "Hello from ${validName}!";\n}\n`;

    // 6. .gitignore
    const gitIgnore = `node_modules\ndist\n*.tgz\n.DS_Store\n`;

    // Write files
    await Bun.write(join(targetDir, "package.json"), JSON.stringify(pkgJson, null, 2));
    await Bun.write(join(targetDir, "tsconfig.json"), JSON.stringify(tsConfig, null, 2));
    await Bun.write(join(targetDir, ".npmrc"), npmRc);
    await Bun.write(join(targetDir, ".gitignore"), gitIgnore);
    await Bun.write(join(targetDir, "src", "index.ts"), indexTs);

    // README.md
    const readme = `# ${validName}\n\nGenerated by AgentRegistry.\n\n## Usage\n\n\`\`\`bash\nnpm install\nnpm run build\nnpm publish\n\`\`\`\n`;
    await Bun.write(join(targetDir, "README.md"), readme);
}
